# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics/v1/analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics/v1/analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61nalytics/v1/analytics.proto\x12\x14onetake.analytics.v1\"\xc7\x01\n\x11TrackEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x12\n\nevent_name\x18\x05 \x01(\t\x12\r\n\x05route\x18\x06 \x01(\t\x12\x13\n\x0b\x65ntity_type\x18\x07 \x01(\t\x12\x11\n\tentity_id\x18\x08 \x01(\t\x12\x12\n\nprops_json\x18\t \x01(\t\x12\x10\n\x08trace_id\x18\n \x01(\t\"5\n\x12TrackEventResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2r\n\x0f\x41nalyticsIngest\x12_\n\nTrackEvent\x12\'.onetake.analytics.v1.TrackEventRequest\x1a(.onetake.analytics.v1.TrackEventResponseB%\xaa\x02\"OneTake.GrpcContracts.Analytics.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics.v1.analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\"OneTake.GrpcContracts.Analytics.V1'
  _globals['_TRACKEVENTREQUEST']._serialized_start=55
  _globals['_TRACKEVENTREQUEST']._serialized_end=254
  _globals['_TRACKEVENTRESPONSE']._serialized_start=256
  _globals['_TRACKEVENTRESPONSE']._serialized_end=309
  _globals['_ANALYTICSINGEST']._serialized_start=311
  _globals['_ANALYTICSINGEST']._serialized_end=425
# @@protoc_insertion_point(module_scope)
