# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reco/v1/reco.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reco/v1/reco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12reco/v1/reco.proto\x12\x0fonetake.reco.v1\"\xa9\x01\n\x19GetRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x11\n\tfeed_type\x18\x03 \x01(\t\x12\x17\n\x0f\x63ontext_post_id\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontext_tags\x18\x05 \x03(\t\x12\x18\n\x10\x65xclude_post_ids\x18\x06 \x03(\t\x12\x10\n\x08trace_id\x18\x07 \x01(\t\"D\n\x12RecommendationItem\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\"P\n\x1aGetRecommendationsResponse\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.onetake.reco.v1.RecommendationItem2|\n\x0bRecoService\x12m\n\x12GetRecommendations\x12*.onetake.reco.v1.GetRecommendationsRequest\x1a+.onetake.reco.v1.GetRecommendationsResponseB \xaa\x02\x1dOneTake.GrpcContracts.Reco.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reco.v1.reco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\035OneTake.GrpcContracts.Reco.V1'
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_start=40
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_end=209
  _globals['_RECOMMENDATIONITEM']._serialized_start=211
  _globals['_RECOMMENDATIONITEM']._serialized_end=279
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_start=281
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_end=361
  _globals['_RECOSERVICE']._serialized_start=363
  _globals['_RECOSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
